### PR TITLE
Fix Bug : key handle error

### PR DESCRIPTION
**Pull request by haz102**
Fixed : key event doesn't fired clearly due to dirty buffers.

### CODE REVIEW

**Comment by haz102** [comment]
@erfanoabdi kindly request, please review this patch.

**Comment by electrikjesus** [comment]
How can we recreate the issue to verify?

**Comment by electrikjesus** [comment]
And some feedback from our discussion: 
Erfan Abdi:
better fix would be using 1 instead of 6 on struct input_event event[6];
and we should do the same for other inputs

1 for keyboard_handle_key
5 for pointer_handle_motion
2 for pointer_handle_button
..

(as many times ADD_EVENT is called on each function)

**Comment by erfanoabdi** [comment]
https://github.com/waydroid/android_hardware_waydroid/commit/bc85e3c88798f6bbecc8fef0fc4d9370f679d83f

Should do the same thing

**Pull request closed without merging**
